[colors.primary]
  background = "#1F1F28"  
  foreground = "#DCD7BA"  

[colors.selection]
  foreground = "#DCA561"
  background = "#223249"  

[colors.normal]
  black   = "#16161D"  
  red     = "#C34043"  
  green   = "#98BB6C"  
  yellow  = "#DCA561"  
  blue    = "#7E9CD8"  
  magenta = "#957FB8"  
  cyan    = "#6A9589"  
  white   = "#DCD7BA"  

[colors.bright]
  black   = "#717C7C"  
  red     = "#E82424"  
  green   = "#76946A"  
  yellow  = "#FF9E3B"  
  blue    = "#658594"  
  magenta = "#938AA9"  
  cyan    = "#7AA89F"  
  white   = "#D27E99"  

[colors]
  indexed_colors =[{index = 16, color = "#E46876"}, {index = 17, color = "#FF5D62"}]  

[font]
size = 12

[window]
padding = {x = 3, y = 3}

[selection]
save_to_clipboard = true

